[workspace]
members = [
    "rust-lang",
    "typescript-lang",
    "javascript-lang",
    "python-lang",
    "go-lang",
    "vue-lang",
    "react-lang",
    "svelte-lang",
    "toml-lang",
    "xml-lang",
    "html-lang",
    "csharp-lang",
    "powershell-lang",
    "spd-lang",
    "json-lang",
    "docker-lang",
    "docker-compose-lang",
]
resolver = "2"
